### ISSUE TITLE
Problema nel tasto home del sito

### ISSUE THREAD

**Issue by JeyDi** [PythonBiellaGroup/ModernPythonDevelopment#1]
Premendo il tasto home all'interno del sito web non si viene reindirizzati in automatico alla home, ma viene visualizzato 404.

La home dovrebbe portare invece alla pagina: pythonbiellagroup.github.io/ModernPythonDevelopment

**Comment by biancini** [comment]
Non riesco a replicare l'errore.
Il tasto Home nel menu mi sembra funzionare correttamente...

Come posso replicare l'errore?
