### ISSUE TITLE
Link Telegram scaduto

### ISSUE THREAD

**Issue by frenkowski** [PythonBiellaGroup/ModernPythonDevelopment#42]
Il [link](https://t.me/joinchat/UZJZzGFKWf9JGGx5) del canale Telegram presente sul [sito-web](https://pythonbiellagroup.it/it/) risulta scaduto e, di conseguenza, non è possibile entrare.

<img width="290" alt="tg" src="https://user-images.githubusercontent.com/14807733/165928633-eb04059f-d86c-4ca4-a307-f8c0c5986b96.png">

**Comment by JeyDi** [comment]
Corretto e pushato nuova versione con intestazione, grazie ancora @frenkowski
